name: demo2-gin-frame
db:
  name: blog
  host: 10.10.243.239:3306
  username: root
  password: root
  charset: utf8mb4
  MaxIdleConns: 10
  MaxOpenConns: 2
redis:
  host: 10.10.243.194
  port: 6379
  auth:
mode: debug
addr: :8080
max_ping_count: 4
log:
  level: debug
  file_format: "%Y%m%d"
  max_save_days: 30
  file_type: one #one, level